baseurl = "https://luciojp.github.io/boqueiraoVI/"
languageCode = "fr-fr"
theme = "hugo-base-theme"
publishDir = "docs"
title = "Açude de Boqueirão"
[params]
  description = "Uma análise sobre os níveis do açude"
  mainIcon = "/img/hugo.png"

